config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "static_pages#index"

  resources :static_pages, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
require "flickr"
require "figaro"
class StaticPagesController < ApplicationController
  def index
    flickr = Flickr.new Figaro.env.flickr_key, Figaro.env.flickr_secret
    debugger

    @photographer = params[:photographer_id]

    begin
      unless @photographer.blank?
        @photo_list = flickr.photos.search(user_id: @photographer)
      end
    rescue StandardError
      flash.now[:error] = "User doesn't exist"
      @photo_list = nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeedMePhotos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash.present?%>
      <div class="flash-message">
        <% flash.each do |name, message| %>
          <div class="<%= name %>"><%= message %></div>
        <% end %>
        </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/_form.html.erb
<%= form_with(model: @static_page, url: static_pages_path, method: :get) do |form| %>
  <%= form.label :photographer_id, "Flickr User Id:" %>
  <%= form.text_field :photographer_id %>
  <%= form.submit 'Submit', class: 'btn' %>
<% end %>

app/views/static_pages/index.html.erb
<h2><%= link_to "Feed Me Photos", root_path %></h2>


 <%= render "form" %>

<% unless flash.present? %>
  <% unless params[:photographer_id].blank? %>
    <div class='user-name'><%= params[:photographer_id] %><span>'s Photostream</span></div>
  <% end %>
<% end %>

<div class="photo-container">
  <% if @photo_list.present? %>
    <% @photo_list.each do |photo| %>
      <div class="photo-frame"><%= image_tag "https://live.staticflickr.com/#{photo["server"]}/#{photo["id"]}_#{photo["secret"]}_n.jpg" %></div>
    <% end %>
  <% end %>
</div>